extensions:
  opamp:
    server:
      http:
        endpoint: http://127.0.0.1:4320/v1/opamp
        polling_interval: 5s
    agent_description:
      non_identifying_attributes:
        "agent.name": "collector1"
        "environment": "development"
        "description": "foobar"
    capabilities:
      reports_health: true
      reports_effective_config: true
      reports_available_components: true

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  extensions: [opamp]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
