extensions:
  opamp:
    server:
      http:
        endpoint: http://127.0.0.1:4320/v1/opamp
        polling_interval: 5s
    agent_description:
      non_identifying_attributes:
        "agent.name": "collector3"
        "description": "foobar"
    capabilities:
      reports_health: true
      reports_effective_config: true
      reports_available_components: true

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4337
      http:
        endpoint: 127.0.0.1:4338

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://127.0.0.1:9999

service:
  telemetry:
    logs:
      level: info
    metrics:
      level: none
  extensions: [opamp]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
