extensions:
  opamp:
    server:
      # ws:
      #   endpoint: "wss://127.0.0.1:4320/v1/opamp"
      #   # Disable verification to test locally.
      #   # Don't do this in production.
      #   tls:
      #     insecure: true
      http:
        endpoint: http://127.0.0.1:4320/v1/opamp
        polling_interval: 10s
    #instance_uid: "1234abcd-8909-4fe9-aff9-b16893516467" # optional
    agent_description:
      non_identifying_attributes:
        "description": "A description here..."
        "foo": "bar"
receivers:
  filelog:
    include: [ file.log ]

exporters:
  debug:
    verbosity: detailed

service:
  extensions: [opamp]  # Enable the OpAMP extension
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [debug]
